name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure
      
    - name: Build Firefox
      run: make build.firefox
      
    - name: Build Chrome
      run: make build.chrome
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: build/artefacts/*.zip
